import os as ps

init = ps.popen('sudo apt-get install figlet')
output1 = init.read(print("\nInitialization Started!\n"))

logo = ps.popen('figlet APACHE2 INSTALLER')
output2 = logo.read()
print(output2)

print("\nStarting Installation Process!\n")
updater1 = ps.popen('sudo apt-get update')
output2 = updater1.read(print("\nUpdating system's repositories lists!\n"))
print("\nSystem's repositories list successfully updated!\n")

print("Starting Apache installation!")
apache = ps.popen('sudo apt-get -y install apache2')
output3 = apache.read(print("\nInstalling Apache2 repository!\n"))
print("\nApache2 successfully installed!\n")

print("Starting PHP installation process!")
phpprop = ps.popen('sudo apt -y install software-properties-common && sudo add-apt-repository ppa:ondrej/php')
output4 = phpprop.read(print("\nAddding php properties!\n"))
updater2 = ps.popen('sudo apt-get update')
output5 = updater2.read(print("\nUpdating repositories list again!\n"))
phpinst = ps.popen('sudo apt -y install php7.4')
output6 = phpinst.read(print("\nInstalling php repository!"))
print("\nphp successfully installed!\n")

phpext = ps.popen('sudo apt-get install php7.4-mysql php7.4-bcmath php7.4-bz2 php7.4-intl php7.4-gd php7.4-mbstring php7.4-zip php7.4-apcu php7.4-uploadprogress php7.4-imagick php7.4-mcrypt php7.4-gettext')
output7 = phpext.read(print("\nAdding some Importent php extentions!\n"))
print("\nExtentions are successfully installed!")

print("\nInitializing mysql-server installation!")
mysqldl = ps.popen('wget https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb')
output8 = mysqldl.read(print("\nMySQL config download completed!"))
print("\nInstalling MySQL in your system!")
mysqlconf = ps.popen('sudo dpkg -i mysql-apt-config*')
output9 = mysqlconf.read(print("\nInstalling MySQL config file!"))
print("\nConfig successfully settled!\n")
mysqlinst = ps.popen('sudo apt-get install mysql-server')
output10 = mysqlinst.read(print("\nInstalling MySQL server!"))
print("\nMySQL successfully installed!\n")
mysqlsetup = ps.popen('mysql_secure_installation')
output11 = mysqlsetup.read(print("\nSetup successfully completed!\n"))

print("\nInitializing PHPMyAdmin installation!\n")
pmarepo = ps.popen('sudo add-apt-repository -y ppa:nijel/phpmyadmin')
output12 = pmarepo.read(print("\nPHPMyAdmin repository list added!\n"))
print("\nUpdating source repositories again!\n")
updater3 = ps.popen('sudo apt-get update')
output13 = updater3.read(print("\nRepositories successfully updated!\n"))
print("\nInstalling PHPMyAdmin in your system!")
pmainst = ps.popen('sudo apt-get -y install phpmyadmin && sudo phpenmod mcrypt && sudo phpenmod mbstring')
output14 = pmainst.read(print("\nPHPMyAdmin Successfully installed!\n"))
 
print("\nInitializing SSL geneeator certbot!\n")
print("\nAdding repository list for certbot!\n")
certbotrepo = ps.popen('sudo add-apt-repository ppa:certbot/certbot')
output15 = certbotrepo.read(print("\nRepository list added successfully!\n"))
print("\nUndating source lists again!\n")
updater4 = ps.popen('sudo apt-get update')
output16 = updater4.read(print("\nRepositories list successfully updated!\n"))
print("\nInstalling certbot in your System!\n")
certbotinst = ps.popen('sudo apt install python-certbot-apache')
output17 = certbotinst.read(print("\nCertbot Successfully installed!\n"))

print("\nRestarting all installed services!\n")
restart = ps.popen('sudo systemctl restart apache2')
output18 = restart.read(print("\nServices restarted!\n"))

final = ps.popen('php -v && apachectl --version && mysql --version')
output19 = final.read()
print(output19)
